//
//  ConstantsAPI.h
//  Party Whale
//
//  Created by Deepu Viswanath on 18/07/12.
//  Copyright (c) 2012 DBG. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface ConstantsAPI : NSObject


//----- API Response Constants  -----//
extern NSString* const URL_API;
extern NSString* const API_DIGITRIBUTE_GETSERVICE_ACTIONAME;
extern NSString* const API_DIGITRIBUTE_GETSERVICE_SECTOKEN;
extern NSString* const API_DIGITRIBUTE_GETDECEASEDDETAILS_ACTIONAME;
extern NSString* const API_DIGITRIBUTE_GETDECEASEDDETAILS_SECTOKEN;
extern NSString* const API_DIGITRIBUTE_GETDECEASEDDETAILS_DECEASEDID;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_ACTIONAME;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_SECTOKEN;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_DECEASEDID;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_FirstName;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_LastName;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_Email;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_Relationship;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_MediaType;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_Subject;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_SENTEMAIL;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_ELAPSEDTIME;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_MEDIALENGTH;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_MRATTEMPT;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_SHAREFB;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_POSTTS;
extern NSString* const API_DIGITRIBUTE_SUBMITDECEASEDDETAILS_DEVICETZ;
@end
